/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TogetherRouteImport } from './routes/together'
import { Route as SouhaylaRouteImport } from './routes/souhayla'
import { Route as MusicRouteImport } from './routes/music'
import { Route as FinaleRouteImport } from './routes/finale'
import { Route as ErminaRouteImport } from './routes/ermina'
import { Route as IndexRouteImport } from './routes/index'

const TogetherRoute = TogetherRouteImport.update({
  id: '/together',
  path: '/together',
  getParentRoute: () => rootRouteImport,
} as any)
const SouhaylaRoute = SouhaylaRouteImport.update({
  id: '/souhayla',
  path: '/souhayla',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const FinaleRoute = FinaleRouteImport.update({
  id: '/finale',
  path: '/finale',
  getParentRoute: () => rootRouteImport,
} as any)
const ErminaRoute = ErminaRouteImport.update({
  id: '/ermina',
  path: '/ermina',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ermina': typeof ErminaRoute
  '/finale': typeof FinaleRoute
  '/music': typeof MusicRoute
  '/souhayla': typeof SouhaylaRoute
  '/together': typeof TogetherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ermina': typeof ErminaRoute
  '/finale': typeof FinaleRoute
  '/music': typeof MusicRoute
  '/souhayla': typeof SouhaylaRoute
  '/together': typeof TogetherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ermina': typeof ErminaRoute
  '/finale': typeof FinaleRoute
  '/music': typeof MusicRoute
  '/souhayla': typeof SouhaylaRoute
  '/together': typeof TogetherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ermina' | '/finale' | '/music' | '/souhayla' | '/together'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ermina' | '/finale' | '/music' | '/souhayla' | '/together'
  id:
    | '__root__'
    | '/'
    | '/ermina'
    | '/finale'
    | '/music'
    | '/souhayla'
    | '/together'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErminaRoute: typeof ErminaRoute
  FinaleRoute: typeof FinaleRoute
  MusicRoute: typeof MusicRoute
  SouhaylaRoute: typeof SouhaylaRoute
  TogetherRoute: typeof TogetherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/together': {
      id: '/together'
      path: '/together'
      fullPath: '/together'
      preLoaderRoute: typeof TogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souhayla': {
      id: '/souhayla'
      path: '/souhayla'
      fullPath: '/souhayla'
      preLoaderRoute: typeof SouhaylaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finale': {
      id: '/finale'
      path: '/finale'
      fullPath: '/finale'
      preLoaderRoute: typeof FinaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ermina': {
      id: '/ermina'
      path: '/ermina'
      fullPath: '/ermina'
      preLoaderRoute: typeof ErminaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErminaRoute: ErminaRoute,
  FinaleRoute: FinaleRoute,
  MusicRoute: MusicRoute,
  SouhaylaRoute: SouhaylaRoute,
  TogetherRoute: TogetherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
